L_SYSTEM_PRESETS = {
    "Fractal Tree": {
        "axiom": "F",
        "rules": {"F": "F[+F]F[-F]F"},
        "angle": 25,
        "iterations": 6,
        "length": 20,
    },
    "Dragon Curve": {
        "axiom": "FX",
        "rules": {"X": "X+YF+", "Y": "-FX-Y"},
        "angle": 90,
        "iterations": 10,
        "length": 10,
    },
    "Sierpinski Triangle": {
        "axiom": "F-G-G",
        "rules": {"F": "F-G+F+G-F", "G": "GG"},
        "angle": 120,
        "iterations": 5,
        "length": 15,
    },
    "Koch Snowflake": {
        "axiom": "F--F--F",
        "rules": {"F": "F+F--F+F"},
        "angle": 60,
        "iterations": 4,
        "length": 15,
    },
    "Fractal Plant": {
        "axiom": "X",
        "rules": {"X": "F-[[X]+X]+F[+FX]-X", "F": "FF"},
        "angle": 25,
        "iterations": 5,
        "length": 15,
    },
    "Crystal": {
        "axiom": "F+F+F+F",
        "rules": {"F": "FF+F++F+F"},
        "angle": 90,
        "iterations": 4,
        "length": 12,
    },
    "Spiral": {
        "axiom": "FX",
        "rules": {"X": "-FX++FY-", "Y": "+FX--FY+"},
        "angle": 60,
        "iterations": 8,
        "length": 8,
    },
    "Hilbert Curve": {
        "axiom": "X",
        "rules": {"X": "-YF+XFX+FY-", "Y": "+XF-YFY-FX+"},
        "angle": 90,
        "iterations": 4,
        "length": 20,
    },
    "Square Fractal": {
        "axiom": "F+F+F+F",
        "rules": {"F": "F+F-F-FF+F+F-F"},
        "angle": 90,
        "iterations": 3,
        "length": 15,
    },
}
